version: "3.8"

services: 
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes: 
            - .:/go/src/go-with-compose
        working_dir: /go/src/go-with-compose      
        links:
            - redis
    redis:
        image: redis:alpine
        ports: 
            - 6379:6379